// Generated by CoffeeScript 1.8.0
(function() {
  var LLApiConfigData, LLApiConfigFilePath, cardConfigUrl, fs, http, phpConfigFilePath, server, serverConfig;

  http = require('http');

  fs = require('fs');

  serverConfig = {
    melot: {
      serverAd: 'http://localhost:9000/lostisland/',
      baseUrl: 'http://localhost:9000/lostisland/index.php/'
    },
    mac: {
      serverAd: 'http://192.168.2.1/',
      baseUrl: 'http://192.168.2.1/index.php/'
    },
    hp: ''
  };

  server = serverConfig.melot;

  phpConfigFilePath = 'application/config/config.php';

  LLApiConfigFilePath = 'Public/js/apis/serverConfig.js';

  LLApiConfigData = 'LLApi.setServerPre("' + server.baseUrl + '");';

  cardConfigUrl = 'apis/cards/card_config_factory/getList/';

  http.get(server.baseUrl + cardConfigUrl, function(_res) {
    var responseStr;
    responseStr = '';
    _res.on('data', function(_chunk) {
      return responseStr += _chunk;
    });
    return _res.on('end', function() {
      return console.log('end => ', responseStr);
    });
  });

  fs.writeFile(LLApiConfigFilePath, LLApiConfigData, function(_err) {
    if (_err) {
      return console.log(_err);
    } else {
      return console.log('set LLApi config success');
    }
  });

  fs.readFile(phpConfigFilePath, function(_err, _data) {
    var content;
    if (_err) {
      console.log(_err);
    }
    content = _data.toString();
    console.log(content.match(/\$config\['base_url'\]([\s\S]{0,25})(;){1}/));
    content = content.replace(/\$config\['base_url'\]([\s\S]{0,25});/, "$config['base_url']='" + server.serverAd + "';");
    return fs.writeFile(phpConfigFilePath, content, function(_err) {
      if (_err) {
        return console.log(_err);
      } else {
        return console.log('set base_url success');
      }
    });
  });

}).call(this);
